version: "3.8"

services:
  email-assistant:
    build: .
    image: email-assistant:latest
    container_name: email-assistant
    restart: unless-stopped
    environment:
      - AUTH_FLOW=${AUTH_FLOW:-web}
      - GOOGLE_OAUTH_CLIENT_JSON=/secrets/credentials.json
      - OAUTH_REDIRECT_URL=${OAUTH_REDIRECT_URL}
      - API_KEY=${API_KEY}
      - DATABASE_URL=postgresql+psycopg2://${POSTGRES_USER:-ea}:${POSTGRES_PASSWORD:-ea}@db:5432/${POSTGRES_DB:-ea}
    volumes:
      - ./files:/app/files
      - ./logs:/app/logs
      - ./secrets:/secrets:ro
      - ./token_store:/app
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://127.0.0.1:5000/api/health"]
      interval: 30s
      timeout: 5s
      retries: 3

  db:
    image: postgres:15
    container_name: email-assistant-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-ea}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-ea}
      - POSTGRES_DB=${POSTGRES_DB:-ea}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
